<!doctype html><html lang=zh dir=auto><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name=robots content="index, follow"><title>Rust的错误处理(一) | 过河卒</title>
<meta name=keywords content="rust,java"><meta name=description content="拉上Java 来谈谈 Rust的错误处理 1 前言 每个语言都会有异常处理机制（没有异常处理机制的语言估计也没有人会用了），Rust 自然也不例外，所以"><meta name=author content="Ramsay Leung"><link rel=canonical href=https://ramsayleung.github.io/zh/post/2018/error_handle_in_rust_1/><meta name=google-site-verification content="XYZabc"><meta name=yandex-verification content="XYZabc"><meta name=msvalidate.01 content="XYZabc"><link crossorigin=anonymous href=/assets/css/stylesheet.cde063907d57a25a10ff526b2714d567a94385b575b3eaa5f581b65b9fcb00a2.css integrity="sha256-zeBjkH1XoloQ/1JrJxTVZ6lDhbV1s+ql9YG2W5/LAKI=" rel="preload stylesheet" as=style><link rel=icon href=https://ramsayleung.github.io/favicon.ico><link rel=icon type=image/png sizes=16x16 href=https://ramsayleung.github.io/favicon-16x16.png><link rel=icon type=image/png sizes=32x32 href=https://ramsayleung.github.io/favicon-32x32.png><link rel=apple-touch-icon href=https://ramsayleung.github.io/apple-touch-icon.png><link rel=mask-icon href=https://ramsayleung.github.io/%3Clink%20/%20abs%20url%3E><meta name=theme-color content="#2e2e33"><meta name=msapplication-TileColor content="#2e2e33"><link rel=alternate hreflang=zh href=https://ramsayleung.github.io/zh/post/2018/error_handle_in_rust_1/><noscript><style>#theme-toggle,.top-link{display:none}</style><style>@media(prefers-color-scheme:dark){:root{--theme:rgb(29, 30, 32);--entry:rgb(46, 46, 51);--primary:rgb(218, 218, 219);--secondary:rgb(155, 156, 157);--tertiary:rgb(65, 66, 68);--content:rgb(196, 196, 197);--code-block-bg:rgb(46, 46, 51);--code-bg:rgb(55, 56, 62);--border:rgb(51, 51, 51)}.list{background:var(--theme)}.list:not(.dark)::-webkit-scrollbar-track{background:0 0}.list:not(.dark)::-webkit-scrollbar-thumb{border-color:var(--theme)}}</style></noscript><script async src="https://www.googletagmanager.com/gtag/js?id=G-9MG65HQHEL"></script><script>var doNotTrack=!1;if(!doNotTrack){window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date),gtag("config","G-9MG65HQHEL",{anonymize_ip:!1})}</script><meta property="og:title" content="Rust的错误处理(一)"><meta property="og:description" content="拉上Java 来谈谈 Rust的错误处理 1 前言 每个语言都会有异常处理机制（没有异常处理机制的语言估计也没有人会用了），Rust 自然也不例外，所以"><meta property="og:type" content="article"><meta property="og:url" content="https://ramsayleung.github.io/zh/post/2018/error_handle_in_rust_1/"><meta property="og:image" content="https://ramsayleung.github.io/%3Clink%20or%20path%20of%20image%20for%20opengraph,%20twitter-cards%3E"><meta property="article:section" content="post"><meta property="article:published_time" content="2018-02-05T20:35:00+08:00"><meta property="article:modified_time" content="2022-02-24T16:38:50+08:00"><meta property="og:site_name" content="Ramsay's Blog"><meta name=twitter:card content="summary_large_image"><meta name=twitter:image content="https://ramsayleung.github.io/%3Clink%20or%20path%20of%20image%20for%20opengraph,%20twitter-cards%3E"><meta name=twitter:title content="Rust的错误处理(一)"><meta name=twitter:description content="拉上Java 来谈谈 Rust的错误处理 1 前言 每个语言都会有异常处理机制（没有异常处理机制的语言估计也没有人会用了），Rust 自然也不例外，所以"><script type=application/ld+json>{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Posts","item":"https://ramsayleung.github.io/zh/post/"},{"@type":"ListItem","position":2,"name":"Rust的错误处理(一)","item":"https://ramsayleung.github.io/zh/post/2018/error_handle_in_rust_1/"}]}</script><script type=application/ld+json>{"@context":"https://schema.org","@type":"BlogPosting","headline":"Rust的错误处理(一)","name":"Rust的错误处理(一)","description":"拉上Java 来谈谈 Rust的错误处理 1 前言 每个语言都会有异常处理机制（没有异常处理机制的语言估计也没有人会用了），Rust 自然也不例外，所以","keywords":["rust","java"],"articleBody":"拉上Java 来谈谈 Rust的错误处理\n1 前言 每个语言都会有异常处理机制（没有异常处理机制的语言估计也没有人会用了），Rust 自然也不例外，所以今天我就来谈Rust 的异常处理，因为 Rust 的异常处理跟常见的语言 （Java/Python 等）的处理机制差异略大，所以打算拉个上个语言，对比着解释. 没错，这 个光荣的任务就落到了 Java 身上\n2 Java 的异常处理 在谈 Rust 的异常处理之前，为了把它们之前的差异讲清楚，先来聊一下 Java 的异常处理。\nFigure 1: Java exception hierarchy\n如上面的简易图所示， Java 的异常都是继承于 Throwable 这个分类的，而异常又是分 成不同的类型： Error, Exception; Exception 又分成 Checked Exception 和 RuntimeException.\nError 一般都是了出现严重的问题，按照JDK 注释的说法，都是不应该 try-catch的：\nAn {() Error} is a subclass of {() Throwable} that indicates serious problems that a reasonable application should not try to catch. Most such errors are abnormal conditions.\n比如虚拟机挂了，或者JRE 出了问题就可能是 Error，前几天我就遇到一个JRE 的 Bug, 整个项目都挂 了：\nFigure 2: JRE fatal error\n我还顺便给 Oracle 报了个Bug :)\n至于RuntimeException 就是类似数组越界，空指针这些异常，即无法在程序编译时发现，只有在运行的时候才会出 现的问题，所以叫做运行时异常(RuntimeException).\n3 Checked Exception Java的Checked Exception, 也就是Java 要求你必须在函数的类型里面声明或处理它可能抛出的异常。比如，你的函数如果是这样：\n1 2 3 4 5 6 7 8 9 10 11 void foo(string filename) throws IOException { File file = new File(filename); BufferedReader br = new BufferedReader(new FileReader(file)); String st; while ((st = br.readLine()) != null) System.out.println(st); } } Java 要求你必须在函数头部写上 throws IOException 或者是必须用 try-catch处理这个异常，因为readline() 的方法签名是：\n1 2 String readLine(boolean ignoreLF) throws IOException { } 所以编译器要求必须要处理这个异常，否则它就不能编译。\n同理，在使用 foo()这个函数 的时候，可能会抛出 IOException 这个异常，由于编译器看到了这个声明，它会严格检 查你对 foo 函数的用法。\n在我看来，CheckedException是Java 优良的设计之一，正因 为Checked Exception的存在，会更容易编写出正确处理错误的程序，更健壮的程序\n4 Rust 的异常处理 Rust 是一个注重安全（Safety）的语言，而错误处理也是 Rust关注的要点之一。\nRust 主要是将错误划分成两种类型，分别是可恢复的错误(recoverable error) 和不可恢复错误 (unrecoverable error).\n出现可恢复的错误的原因多种多样，例如打开文件的时候，文件找不到或者没有读权限等，开发者就应该对这种可能出现的错误进行处理；\n而不可恢复的错误就可能是Bug 引起的，比如数组越界等。而其他常见的语言一般是没有没有区分 recoverable error和 unrecoverable error的. 比如 Python, 用的就是 Exception.\n而Rust 是没有 Exception, Rust 用 Result 表示可恢复错误， 用 panic!() 来表示出现错误，并且中断程序的执行并退出(不可恢复错误)。\nResult 是Rust 标准库的枚举：\n1 2 3 4 pub enum Result\u003cT, E\u003e { Ok(T), Err(E), } T和E都是泛型，T表示程序执行正常的时候的返回值，那E自然是程序出错时的返回 值。以标准库的打开文件的函数为例， std::io::File 的 open() 函数的签名如下：\n1 2 3 pub fn open\u003cP: AsRef\u003cPath\u003e\u003e(path: P) -\u003e io::Result\u003cFile\u003e { OpenOptions::new().read(true).open(path.as_ref()) } 忽略这个方法的参数，只看返回值类型：io::Result, 又因为有 type Result Result;=\n这个 typedef 语句，所以返回值的完整版本时io::Result, 即调用 open 这个函数的时候，可能出现错误，出现错误时候返回一个 io::Error, 如果调用open没有问题的话，就会返回一个 File 的结构体，所以这个就类似 Java 的CheckedException,\n只要声明了函数可能出现问题，在调用函数的时候就必须处理可能出现的错误，不然编译器就不会让你通过(Rust 的编译器就像位父亲那样对开发者耳提面命), 例如：\n1 2 3 4 5 6 match File::open(\u0026self.cache_path) { Ok(file) =\u003e println!(\"{:?}\",file), Err(why) =\u003e { panic!(\"couldn't open {:?}\", why.description()) } }; 5 Java 的异常传递 在程序中，总会有一些错误需要处理，但是却不应该在错误出现的函数进行处理的情况(或者是，你很懒惰，只想应付一下编译器，不想处理出现的异常 :)\n比如你正在编写一个类 库，里面有很多的IO 操作，有IO 操作的地方就有可能出现IOException. 如果出现异常， 你不应该自己在类库把异常给 try-catch了，如果这样，使用你类库的开发者就没办法知 道程序出现了异常，异常的堆栈也丢了。\n比较合理的做法是，把IOException捕捉了，然后对 IOException 做一层包装，然后再抛给类库的调用者，例如：\n1 2 3 4 5 6 7 8 9 10 11 public void doSomething() throws WrappingException{ try{ doSomethingThatCanThrowException(); } catch (SomeException e){ e.addContextInformation(\"there is something happen in doSomething() function, `Some Exception` is raised, balabala\"); //throw e; //throw e, or wrap it see next line. throw new WrappingException(e, more information about Some Exception, balabala); } finally { //clean up close open resources etc. } } 当然，你也可以在添加了额外的信息之后，直接把原来的异常抛出来\n6 Rust 的异常传递 刚刚谈了 Java 的异常传递，现在轮到 Rust 的异常传递了，既然Rust 没有 Exception一说，那 Rust 传递的自然也是 Result 这个枚举类型(这里针对的是 可恢复错误，不可恢复错误出现错误的时候，会返回错误并弹出程序，自然不存在异常传递).\n先来看看 Rust 的异常传递的例子：\n1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 use std::io; use std::io::Read; use std::fs::File; fn read_username_from_file() -\u003e Result { let f = File::open(\"hello.txt\"); let mut f = match f { Ok(file) =\u003e file, Err(e) =\u003e return Err(e), }; let mut s = String::new(); match f.read_to_string(\u0026mut s) { Ok(_) =\u003e Ok(s), Err(e) =\u003e Err(e), } } 例子来自 Rust Book\n先来看看函数的返回值 Result, 也就是说， read_username_from_file 正确执行的时候返回是 String, 错误的时候，返回的是 io::Error. 这里的异常传递是在出现 io::Error的时候，将错误原样返回，不然就是返 回函数执行成功的结果。\n就异常传递的方式而言，Rust 和 Java 是大同小异：声明可能抛出的异常和成功时返回的结果，然后在遇到错误的时候，直接（或者包装一下）返回错误。\n6.1 ? 关键字 虽说 Rust 的异常处理很清晰，但是每次都要 match 然后返回未免太繁琐了，所以 Rust 提供了一个语法糖来显示繁琐的异常传递：用 “?” 关键字进行异常传递：\n1 2 3 4 5 6 7 8 9 10 use std::io; use std::io::Read; use std::fs::File; fn read_username_from_file() -\u003e Result\u003cString, io::Error\u003e { let mut f = File::open(\"hello.txt\")?; let mut s = String::new(); f.read_to_string(\u0026mut s)?; Ok(s) } 同样的功能，但是模板代码却减少了很多 :)\n6.2 unwrap 和 expect 虽说 Rust 的可恢复错误设计得很优雅，但是每次遇到可能出现错误得地方都要显示地进行 处理，不免让人觉得繁琐.\nRust 也考虑到这种情况了，提供了 unwrap() 和 expect()让你舒心简单粗暴地处理错误：在函数调用成功的时候返回正确的结果，在 出现错误地时候直接 panic!(),并退出程序\n6.2.1 unwrap 1 2 3 fn main() { let f = File::open(\"hello.txt\").unwrap(); } 打开 hello.txt这个文件，能打开就返回文件 f,不能打开就 panic!() 然后退出程序。\n1 2 3 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: \"No such file or directory\" } }', /stable-dist-rustc/build/src/libcore/result.rs:868 6.2.2 expect expect()和 unwrap()类似，只不过 expect()可以加上额外的信息：\n1 2 3 4 5 use std::fs::File; fn main() { let f = File::open(\"hello.txt\").expect(\"Failed to open hello.txt\"); } 出现错误的时候，除了显示应有的错误信息之外，还会显示你自定义的错误信息：\n1 2 3 thread 'main' panicked at 'Failed to open hello.txt: Error { repr: Os { code: 2, message: \"No such file or directory\" } }', /stable-dist-rustc/build/src/libcore/result.rs:868 以上代码来自 Rust book\n7 结语 以上只是浅谈了 Rust 的错误处理，以及和 Java 的异常处理机制的简单比较，接下来我会 谈谈如何自定义Error以及使用 erro_chain 这个库来优雅地进行错误处理 :)\n如果想了解更多关于 Rust 异常处理的内容，可以查阅 Rust book Error handle\n8 参考 propagating exceptions Rust book IO Result 公号同步更新，欢迎关注👻 ","wordCount":"2750","inLanguage":"zh","image":"https://ramsayleung.github.io/%3Clink%20or%20path%20of%20image%20for%20opengraph,%20twitter-cards%3E","datePublished":"2018-02-05T20:35:00+08:00","dateModified":"2022-02-24T16:38:50+08:00","author":{"@type":"Person","name":"Ramsay Leung"},"mainEntityOfPage":{"@type":"WebPage","@id":"https://ramsayleung.github.io/zh/post/2018/error_handle_in_rust_1/"},"publisher":{"@type":"Organization","name":"过河卒","logo":{"@type":"ImageObject","url":"https://ramsayleung.github.io/favicon.ico"}}}</script></head><body id=top><script>localStorage.getItem("pref-theme")==="dark"?document.body.classList.add("dark"):localStorage.getItem("pref-theme")==="light"?document.body.classList.remove("dark"):window.matchMedia("(prefers-color-scheme: dark)").matches&&document.body.classList.add("dark")</script><header class=header><nav class=nav><div class=logo><a href=https://ramsayleung.github.io/zh/ accesskey=h title="Home (Alt + H)"><img src=https://ramsayleung.github.io/apple-touch-icon.png alt aria-label=logo height=35>Home</a><div class=logo-switches><button id=theme-toggle accesskey=t title="(Alt + T)"><svg id="moon" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"/></svg><svg id="sun" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg></button><ul class=lang-switch><li>|</li><li><a href=https://ramsayleung.github.io/en/ title=English aria-label=English>En</a></li></ul></div></div><ul id=menu><li class=dropdown><a href=https://ramsayleung.github.io/zh/categories/ title="系列 "><span>系列 ▾</span></a><div class="menu-more-content dropdown-content"><a href=https://ramsayleung.github.io/zh/categories/%E5%BE%97%E5%A4%B1%E6%84%9F%E6%82%9F/ title=得失感悟><span>得失感悟
</span></a><a href=https://ramsayleung.github.io/zh/categories/%E6%97%85%E5%8A%A0%E7%BB%8F%E5%8E%86 title=旅加经历><span>旅加经历
</span></a><a href=https://ramsayleung.github.io/zh/categories/%E5%B7%A5%E4%BD%9C%E6%B5%81/ title=我的工作流><span>我的工作流
</span></a><a href=https://ramsayleung.github.io/zh/categories/%E6%B5%8B%E8%AF%95%E6%8A%80%E8%83%BD%E8%BF%9B%E9%98%B6/ title=测试技能进阶><span>测试技能进阶
</span></a><a href=https://ramsayleung.github.io/zh/categories/%E8%BD%AF%E4%BB%B6%E5%B7%A5%E7%A8%8B%E5%B8%88%E7%9A%84%E8%BD%AF%E6%8A%80%E8%83%BD%E6%8C%87%E5%8C%97/ title=软件工程师的软技能指北><span>软件工程师的软技能指北
</span></a><a href=https://ramsayleung.github.io/zh/categories/reinvent-%E9%87%8D%E6%96%B0%E9%80%A0%E8%BD%AE%E5%AD%90%E7%B3%BB%E5%88%97 title=Reinvent-重新造轮子系列><span>Reinvent-重新造轮子系列</span></a></div></li><li><a href=https://ramsayleung.github.io/zh/archives/ title=归档><span>归档</span></a></li><li><a href=https://ramsayleung.github.io/zh/search/ title=搜索><span>搜索</span></a></li><li><a href=https://ramsayleung.github.io/zh/tags/ title=标签><span>标签</span></a></li><li><a href=https://ramsayleung.github.io/zh/about_me_zh/ title=关于><span>关于</span></a></li><li><a href=https://ramsayleung.github.io/zh/index.xml title=RSS><span>RSS</span></a></li></ul></nav></header><main class=main><article class=post-single><header class=post-header><div class=breadcrumbs><a href=https://ramsayleung.github.io/zh/>主页</a>&nbsp;»&nbsp;<a href=https://ramsayleung.github.io/zh/post/>Posts</a></div><h1 class="post-title entry-hint-parent">Rust的错误处理(一)</h1><div class=post-meta><span title='2018-02-05 20:35:00 +0800 +0800'>二月 5, 2018</span>&nbsp;·&nbsp;6 分钟&nbsp;·&nbsp;2750 字&nbsp;·&nbsp;Ramsay Leung&nbsp;|&nbsp;<a href=https://github.com/ramsayleung/ramsayleung.github.io/blob/master/content/post/2018/error_handle_in_rust_1.md rel="noopener noreferrer" target=_blank>Suggest Changes</a></div></header><div class=toc><details><summary accesskey=c title="(Alt + C)"><span class=details>目录</span></summary><div class=inner><nav id=TableOfContents><ul><li><a href=#前言><span class=section-num>1</span> 前言</a></li><li><a href=#java-的异常处理><span class=section-num>2</span> Java 的异常处理</a></li><li><a href=#checked-exception><span class=section-num>3</span> Checked Exception</a></li><li><a href=#rust-的异常处理><span class=section-num>4</span> Rust 的异常处理</a></li><li><a href=#java-的异常传递><span class=section-num>5</span> Java 的异常传递</a></li><li><a href=#rust-的异常传递><span class=section-num>6</span> Rust 的异常传递</a><ul><li><a href=#关键字><span class=section-num>6.1</span> ? 关键字</a></li><li><a href=#unwrap-和-expect><span class=section-num>6.2</span> unwrap 和 expect</a></li></ul></li><li><a href=#结语><span class=section-num>7</span> 结语</a></li><li><a href=#参考><span class=section-num>8</span> 参考</a></li></ul></nav></div></details></div><div class=post-content><p>拉上Java 来谈谈 Rust的错误处理</p><h2 id=前言><span class=section-num>1</span> 前言<a hidden class=anchor aria-hidden=true href=#前言>#</a></h2><p>每个语言都会有异常处理机制（没有异常处理机制的语言估计也没有人会用了），Rust 自然也不例外，所以今天我就来谈Rust 的异常处理，因为 Rust 的异常处理跟常见的语言 （Java/Python 等）的处理机制差异略大，所以打算拉个上个语言，对比着解释. 没错，这 个光荣的任务就落到了 Java 身上</p><h2 id=java-的异常处理><span class=section-num>2</span> Java 的异常处理<a hidden class=anchor aria-hidden=true href=#java-的异常处理>#</a></h2><p>在谈 Rust 的异常处理之前，为了把它们之前的差异讲清楚，先来聊一下 Java 的异常处理。</p><figure><input type=checkbox id=zoomCheck-4ffb2 hidden>
<label for=zoomCheck-4ffb2><img class=zoomCheck loading=lazy src=https://raw.githubusercontent.com/ramsayleung/images/master/java_exception_hierarchy.png alt="Figure 1: Java exception hierarchy"></label><figcaption><p><span class=figure-number>Figure 1: </span>Java exception hierarchy</p></figcaption></figure><p>如上面的简易图所示， Java 的异常都是继承于 <code>Throwable</code> 这个分类的，而异常又是分 成不同的类型： <code>Error</code>, <code>Exception</code>;
<code>Exception</code> 又分成 <code>Checked Exception</code> 和 <code>RuntimeException</code>.</p><p><code>Error</code> 一般都是了出现严重的问题，按照JDK 注释的说法，都是不应该 <code>try-catch</code>的：</p><blockquote><p>An {() Error} is a subclass of {() Throwable}
that indicates serious problems that a reasonable application should
not try to catch. Most such errors are abnormal conditions.</p></blockquote><p>比如虚拟机挂了，或者JRE 出了问题就可能是 <code>Error</code>，前几天我就遇到一个JRE 的 Bug, 整个项目都挂 了：</p><figure><input type=checkbox id=zoomCheck-ac0ab hidden>
<label for=zoomCheck-ac0ab><img class=zoomCheck loading=lazy src=https://raw.githubusercontent.com/ramsayleung/images/master/20191104104407.png alt="Figure 2: JRE fatal error"></label><figcaption><p><span class=figure-number>Figure 2: </span>JRE fatal error</p></figcaption></figure><p>我还顺便给 Oracle 报了个<a href="https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8196769">Bug</a> :)</p><p>至于<code>RuntimeException</code> 就是类似数组越界，空指针这些异常，即无法在程序编译时发现，只有在运行的时候才会出 现的问题，所以叫做运行时异常(<code>RuntimeException</code>).</p><h2 id=checked-exception><span class=section-num>3</span> Checked Exception<a hidden class=anchor aria-hidden=true href=#checked-exception>#</a></h2><p>Java的<code>Checked Exception</code>, 也就是Java 要求你必须在函数的类型里面声明或处理它可能抛出的异常。比如，你的函数如果是这样：</p><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre tabindex=0 class=chroma><code><span class=lnt> 1
</span><span class=lnt> 2
</span><span class=lnt> 3
</span><span class=lnt> 4
</span><span class=lnt> 5
</span><span class=lnt> 6
</span><span class=lnt> 7
</span><span class=lnt> 8
</span><span class=lnt> 9
</span><span class=lnt>10
</span><span class=lnt>11
</span></code></pre></td><td class=lntd><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=kt>void</span><span class=w> </span><span class=nf>foo</span><span class=p>(</span><span class=n>string</span><span class=w> </span><span class=n>filename</span><span class=p>)</span><span class=w> </span><span class=kd>throws</span><span class=w> </span><span class=n>IOException</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=n>File</span><span class=w> </span><span class=n>file</span><span class=w> </span><span class=o>=</span><span class=w> </span><span class=k>new</span><span class=w> </span><span class=n>File</span><span class=p>(</span><span class=n>filename</span><span class=p>);</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=n>BufferedReader</span><span class=w> </span><span class=n>br</span><span class=w> </span><span class=o>=</span><span class=w> </span><span class=k>new</span><span class=w> </span><span class=n>BufferedReader</span><span class=p>(</span><span class=k>new</span><span class=w> </span><span class=n>FileReader</span><span class=p>(</span><span class=n>file</span><span class=p>));</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=n>String</span><span class=w> </span><span class=n>st</span><span class=p>;</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=k>while</span><span class=w> </span><span class=p>((</span><span class=n>st</span><span class=w> </span><span class=o>=</span><span class=w> </span><span class=n>br</span><span class=p>.</span><span class=na>readLine</span><span class=p>())</span><span class=w> </span><span class=o>!=</span><span class=w> </span><span class=kc>null</span><span class=p>)</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>	</span><span class=n>System</span><span class=p>.</span><span class=na>out</span><span class=p>.</span><span class=na>println</span><span class=p>(</span><span class=n>st</span><span class=p>);</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span></code></pre></td></tr></table></div></div><p>Java 要求你必须在函数头部写上 <code>throws IOException</code> 或者是必须用 <code>try-catch</code>处理这个异常，因为<code>readline()</code> 的方法签名是：</p><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre tabindex=0 class=chroma><code><span class=lnt>1
</span><span class=lnt>2
</span></code></pre></td><td class=lntd><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=n>String</span><span class=w> </span><span class=nf>readLine</span><span class=p>(</span><span class=kt>boolean</span><span class=w> </span><span class=n>ignoreLF</span><span class=p>)</span><span class=w> </span><span class=kd>throws</span><span class=w> </span><span class=n>IOException</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span></code></pre></td></tr></table></div></div><p>所以编译器要求必须要处理这个异常，否则它就不能编译。</p><p>同理，在使用 <code>foo()</code>这个函数 的时候，可能会抛出 <code>IOException</code> 这个异常，由于编译器看到了这个声明，它会严格检 查你对 <code>foo</code>
函数的用法。</p><p>在我看来，<code>CheckedException</code>是Java 优良的设计之一，正因 为<code>Checked Exception</code>的存在，会更容易编写出正确处理错误的程序，更健壮的程序</p><h2 id=rust-的异常处理><span class=section-num>4</span> Rust 的异常处理<a hidden class=anchor aria-hidden=true href=#rust-的异常处理>#</a></h2><p>Rust 是一个注重安全（Safety）的语言，而错误处理也是 Rust关注的要点之一。</p><p>Rust 主要是将错误划分成两种类型，分别是可恢复的错误(recoverable error) 和不可恢复错误 (unrecoverable error).</p><p>出现可恢复的错误的原因多种多样，例如打开文件的时候，文件找不到或者没有读权限等，开发者就应该对这种可能出现的错误进行处理；</p><p>而不可恢复的错误就可能是Bug 引起的，比如数组越界等。而其他常见的语言一般是没有没有区分 <code>recoverable error</code>和 <code>unrecoverable error</code>的. 比如 Python, 用的就是 <code>Exception</code>.</p><p>而Rust 是没有 <code>Exception</code>, Rust 用 <code>Result&lt;T, E></code> 表示可恢复错误， 用 <code>panic!()</code> 来表示出现错误，并且中断程序的执行并退出(不可恢复错误)。</p><p><code>Result</code> 是Rust 标准库的枚举：</p><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre tabindex=0 class=chroma><code><span class=lnt>1
</span><span class=lnt>2
</span><span class=lnt>3
</span><span class=lnt>4
</span></code></pre></td><td class=lntd><pre tabindex=0 class=chroma><code class=language-rust data-lang=rust><span class=line><span class=cl><span class=k>pub</span><span class=w> </span><span class=k>enum</span> <span class=nb>Result</span><span class=o>&lt;</span><span class=n>T</span><span class=p>,</span><span class=w> </span><span class=n>E</span><span class=o>&gt;</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=nb>Ok</span><span class=p>(</span><span class=n>T</span><span class=p>),</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=nb>Err</span><span class=p>(</span><span class=n>E</span><span class=p>),</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span></code></pre></td></tr></table></div></div><p><code>T</code>和<code>E</code>都是泛型，<code>T</code>表示程序执行正常的时候的返回值，那<code>E</code>自然是程序出错时的返回 值。以标准库的打开文件的函数为例， <code>std::io::File</code> 的 <code>open()</code> 函数的签名如下：</p><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre tabindex=0 class=chroma><code><span class=lnt>1
</span><span class=lnt>2
</span><span class=lnt>3
</span></code></pre></td><td class=lntd><pre tabindex=0 class=chroma><code class=language-rust data-lang=rust><span class=line><span class=cl><span class=k>pub</span><span class=w> </span><span class=k>fn</span> <span class=nf>open</span><span class=o>&lt;</span><span class=n>P</span>: <span class=nb>AsRef</span><span class=o>&lt;</span><span class=n>Path</span><span class=o>&gt;&gt;</span><span class=p>(</span><span class=n>path</span>: <span class=nc>P</span><span class=p>)</span><span class=w> </span>-&gt; <span class=nc>io</span>::<span class=nb>Result</span><span class=o>&lt;</span><span class=n>File</span><span class=o>&gt;</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=n>OpenOptions</span>::<span class=n>new</span><span class=p>().</span><span class=n>read</span><span class=p>(</span><span class=kc>true</span><span class=p>).</span><span class=n>open</span><span class=p>(</span><span class=n>path</span><span class=p>.</span><span class=n>as_ref</span><span class=p>())</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span></code></pre></td></tr></table></div></div><p>忽略这个方法的参数，只看返回值类型：<code>io::Result&lt;File></code>, 又因为有 <code>type Result&lt;T></code> Result&lt;T, Error>;=</p><p>这个 <code>typedef</code> 语句，所以返回值的完整版本时<code>io::Result&lt;File,io::Error></code>, 即调用 <code>open</code> 这个函数的时候，可能出现错误，出现错误时候返回一个 <code>io::Error</code>, 如果调用<code>open</code>没有问题的话，就会返回一个 <code>File</code> 的结构体，所以这个就类似 Java 的<code>CheckedException</code>,</p><p>只要声明了函数可能出现问题，在调用函数的时候就必须处理可能出现的错误，不然编译器就不会让你通过(Rust 的编译器就像位父亲那样对开发者耳提面命), 例如：</p><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre tabindex=0 class=chroma><code><span class=lnt>1
</span><span class=lnt>2
</span><span class=lnt>3
</span><span class=lnt>4
</span><span class=lnt>5
</span><span class=lnt>6
</span></code></pre></td><td class=lntd><pre tabindex=0 class=chroma><code class=language-rust data-lang=rust><span class=line><span class=cl><span class=k>match</span><span class=w> </span><span class=n>File</span>::<span class=n>open</span><span class=p>(</span><span class=o>&amp;</span><span class=bp>self</span><span class=p>.</span><span class=n>cache_path</span><span class=p>)</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=nb>Ok</span><span class=p>(</span><span class=n>file</span><span class=p>)</span><span class=w> </span><span class=o>=&gt;</span><span class=w> </span><span class=fm>println!</span><span class=p>(</span><span class=s>&#34;</span><span class=si>{:?}</span><span class=s>&#34;</span><span class=p>,</span><span class=n>file</span><span class=p>),</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=nb>Err</span><span class=p>(</span><span class=n>why</span><span class=p>)</span><span class=w> </span><span class=o>=&gt;</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>	</span><span class=fm>panic!</span><span class=p>(</span><span class=s>&#34;couldn&#39;t open </span><span class=si>{:?}</span><span class=s>&#34;</span><span class=p>,</span><span class=w> </span><span class=n>why</span><span class=p>.</span><span class=n>description</span><span class=p>())</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=p>}</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>};</span><span class=w>
</span></span></span></code></pre></td></tr></table></div></div><h2 id=java-的异常传递><span class=section-num>5</span> Java 的异常传递<a hidden class=anchor aria-hidden=true href=#java-的异常传递>#</a></h2><p>在程序中，总会有一些错误需要处理，但是却不应该在错误出现的函数进行处理的情况(或者是，你很懒惰，只想应付一下编译器，不想处理出现的异常 :)</p><p>比如你正在编写一个类 库，里面有很多的IO 操作，有IO 操作的地方就有可能出现<code>IOException</code>. 如果出现异常，
你不应该自己在类库把异常给 <code>try-catch</code>了，如果这样，使用你类库的开发者就没办法知 道程序出现了异常，异常的堆栈也丢了。</p><p>比较合理的做法是，把<code>IOException</code>捕捉了，然后对 <code>IOException</code> 做一层包装，然后再抛给类库的调用者，例如：</p><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre tabindex=0 class=chroma><code><span class=lnt> 1
</span><span class=lnt> 2
</span><span class=lnt> 3
</span><span class=lnt> 4
</span><span class=lnt> 5
</span><span class=lnt> 6
</span><span class=lnt> 7
</span><span class=lnt> 8
</span><span class=lnt> 9
</span><span class=lnt>10
</span><span class=lnt>11
</span></code></pre></td><td class=lntd><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=kd>public</span><span class=w> </span><span class=kt>void</span><span class=w> </span><span class=nf>doSomething</span><span class=p>()</span><span class=w> </span><span class=kd>throws</span><span class=w> </span><span class=n>WrappingException</span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=k>try</span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>	</span><span class=n>doSomethingThatCanThrowException</span><span class=p>();</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=p>}</span><span class=w> </span><span class=k>catch</span><span class=w> </span><span class=p>(</span><span class=n>SomeException</span><span class=w> </span><span class=n>e</span><span class=p>){</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>	</span><span class=n>e</span><span class=p>.</span><span class=na>addContextInformation</span><span class=p>(</span><span class=s>&#34;there is something happen in doSomething() function, `Some Exception` is raised, balabala&#34;</span><span class=p>);</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>	</span><span class=c1>//throw e;  //throw e, or wrap it  see next line.</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>	</span><span class=k>throw</span><span class=w> </span><span class=k>new</span><span class=w> </span><span class=n>WrappingException</span><span class=p>(</span><span class=n>e</span><span class=p>,</span><span class=w> </span><span class=n>more</span><span class=w> </span><span class=n>information</span><span class=w> </span><span class=n>about</span><span class=w> </span><span class=n>Some</span><span class=w> </span><span class=n>Exception</span><span class=p>,</span><span class=w> </span><span class=n>balabala</span><span class=p>);</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=p>}</span><span class=w> </span><span class=k>finally</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>	</span><span class=c1>//clean up close open resources etc.</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=p>}</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span></code></pre></td></tr></table></div></div><p>当然，你也可以在添加了额外的信息之后，直接把原来的异常抛出来</p><h2 id=rust-的异常传递><span class=section-num>6</span> Rust 的异常传递<a hidden class=anchor aria-hidden=true href=#rust-的异常传递>#</a></h2><p>刚刚谈了 Java 的异常传递，现在轮到 Rust 的异常传递了，既然Rust 没有 <code>Exception</code>一说，那 Rust 传递的自然也是 <code>Result&lt;T,E></code>
这个枚举类型(这里针对的是 可恢复错误，不可恢复错误出现错误的时候，会返回错误并弹出程序，自然不存在异常传递).</p><p>先来看看 Rust 的异常传递的例子：</p><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre tabindex=0 class=chroma><code><span class=lnt> 1
</span><span class=lnt> 2
</span><span class=lnt> 3
</span><span class=lnt> 4
</span><span class=lnt> 5
</span><span class=lnt> 6
</span><span class=lnt> 7
</span><span class=lnt> 8
</span><span class=lnt> 9
</span><span class=lnt>10
</span><span class=lnt>11
</span><span class=lnt>12
</span><span class=lnt>13
</span><span class=lnt>14
</span><span class=lnt>15
</span><span class=lnt>16
</span><span class=lnt>17
</span><span class=lnt>18
</span><span class=lnt>19
</span></code></pre></td><td class=lntd><pre tabindex=0 class=chroma><code class=language-fallback data-lang=fallback><span class=line><span class=cl>use std::io;
</span></span><span class=line><span class=cl>use std::io::Read;
</span></span><span class=line><span class=cl>use std::fs::File;
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>fn read_username_from_file() -&gt; Result&lt;String, io::Error&gt; {
</span></span><span class=line><span class=cl>    let f = File::open(&#34;hello.txt&#34;);
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    let mut f = match f {
</span></span><span class=line><span class=cl>	Ok(file) =&gt; file,
</span></span><span class=line><span class=cl>	Err(e) =&gt; return Err(e),
</span></span><span class=line><span class=cl>    };
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    let mut s = String::new();
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    match f.read_to_string(&amp;mut s) {
</span></span><span class=line><span class=cl>	Ok(_) =&gt; Ok(s),
</span></span><span class=line><span class=cl>	Err(e) =&gt; Err(e),
</span></span><span class=line><span class=cl>    }
</span></span><span class=line><span class=cl>}
</span></span></code></pre></td></tr></table></div></div><p>例子来自 Rust Book</p><p>先来看看函数的返回值 <code>Result&lt;String,io::Error></code>, 也就是说， <code>read_username_from_file</code> 正确执行的时候返回是 <code>String</code>,
错误的时候，返回的是 <code>io::Error</code>. 这里的异常传递是在出现 <code>io::Error</code>的时候，将错误原样返回，不然就是返
回函数执行成功的结果。</p><p>就异常传递的方式而言，Rust 和 Java 是大同小异：声明可能抛出的异常和成功时返回的结果，然后在遇到错误的时候，直接（或者包装一下）返回错误。</p><h3 id=关键字><span class=section-num>6.1</span> ? 关键字<a hidden class=anchor aria-hidden=true href=#关键字>#</a></h3><p>虽说 Rust 的异常处理很清晰，但是每次都要 <code>match</code> 然后返回未免太繁琐了，所以 Rust 提供了一个语法糖来显示繁琐的异常传递：用
&ldquo;?&rdquo; 关键字进行异常传递：</p><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre tabindex=0 class=chroma><code><span class=lnt> 1
</span><span class=lnt> 2
</span><span class=lnt> 3
</span><span class=lnt> 4
</span><span class=lnt> 5
</span><span class=lnt> 6
</span><span class=lnt> 7
</span><span class=lnt> 8
</span><span class=lnt> 9
</span><span class=lnt>10
</span></code></pre></td><td class=lntd><pre tabindex=0 class=chroma><code class=language-rust data-lang=rust><span class=line><span class=cl><span class=k>use</span><span class=w> </span><span class=n>std</span>::<span class=n>io</span><span class=p>;</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=k>use</span><span class=w> </span><span class=n>std</span>::<span class=n>io</span>::<span class=n>Read</span><span class=p>;</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=k>use</span><span class=w> </span><span class=n>std</span>::<span class=n>fs</span>::<span class=n>File</span><span class=p>;</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=k>fn</span> <span class=nf>read_username_from_file</span><span class=p>()</span><span class=w> </span>-&gt; <span class=nb>Result</span><span class=o>&lt;</span><span class=nb>String</span><span class=p>,</span><span class=w> </span><span class=n>io</span>::<span class=n>Error</span><span class=o>&gt;</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=kd>let</span><span class=w> </span><span class=k>mut</span><span class=w> </span><span class=n>f</span><span class=w> </span><span class=o>=</span><span class=w> </span><span class=n>File</span>::<span class=n>open</span><span class=p>(</span><span class=s>&#34;hello.txt&#34;</span><span class=p>)</span><span class=o>?</span><span class=p>;</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=kd>let</span><span class=w> </span><span class=k>mut</span><span class=w> </span><span class=n>s</span><span class=w> </span><span class=o>=</span><span class=w> </span><span class=nb>String</span>::<span class=n>new</span><span class=p>();</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=n>f</span><span class=p>.</span><span class=n>read_to_string</span><span class=p>(</span><span class=o>&amp;</span><span class=k>mut</span><span class=w> </span><span class=n>s</span><span class=p>)</span><span class=o>?</span><span class=p>;</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=nb>Ok</span><span class=p>(</span><span class=n>s</span><span class=p>)</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span></code></pre></td></tr></table></div></div><p>同样的功能，但是模板代码却减少了很多 :)</p><h3 id=unwrap-和-expect><span class=section-num>6.2</span> unwrap 和 expect<a hidden class=anchor aria-hidden=true href=#unwrap-和-expect>#</a></h3><p>虽说 Rust 的可恢复错误设计得很优雅，但是每次遇到可能出现错误得地方都要显示地进行 处理，不免让人觉得繁琐.</p><p>Rust 也考虑到这种情况了，提供了 <code>unwrap()</code> 和 <code>expect()</code>让你舒心<del>简单粗暴</del>地处理错误：在函数调用成功的时候返回正确的结果，在 出现错误地时候直接 <code>panic!()</code>,并退出程序</p><h4 id=unwrap><span class=section-num>6.2.1</span> unwrap<a hidden class=anchor aria-hidden=true href=#unwrap>#</a></h4><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre tabindex=0 class=chroma><code><span class=lnt>1
</span><span class=lnt>2
</span><span class=lnt>3
</span></code></pre></td><td class=lntd><pre tabindex=0 class=chroma><code class=language-rust data-lang=rust><span class=line><span class=cl><span class=k>fn</span> <span class=nf>main</span><span class=p>()</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=kd>let</span><span class=w> </span><span class=n>f</span><span class=w> </span><span class=o>=</span><span class=w> </span><span class=n>File</span>::<span class=n>open</span><span class=p>(</span><span class=s>&#34;hello.txt&#34;</span><span class=p>).</span><span class=n>unwrap</span><span class=p>();</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span></code></pre></td></tr></table></div></div><p>打开 <code>hello.txt</code>这个文件，能打开就返回文件 <code>f</code>,不能打开就 <code>panic!()</code> 然后退出程序。</p><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre tabindex=0 class=chroma><code><span class=lnt>1
</span><span class=lnt>2
</span><span class=lnt>3
</span></code></pre></td><td class=lntd><pre tabindex=0 class=chroma><code class=language-mysql data-lang=mysql><span class=line><span class=cl><span class=n>thread</span><span class=w> </span><span class=s1>&#39;main&#39;</span><span class=w> </span><span class=n>panicked</span><span class=w> </span><span class=n>at</span><span class=w> </span><span class=s1>&#39;called `Result::unwrap()` on an `Err` value: Error {
</span></span></span><span class=line><span class=cl><span class=s1>repr: Os { code: 2, message: &#34;No such file or directory&#34; } }&#39;</span><span class=p>,</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=o>/</span><span class=n>stable</span><span class=o>-</span><span class=n>dist</span><span class=o>-</span><span class=n>rustc</span><span class=o>/</span><span class=n>build</span><span class=o>/</span><span class=n>src</span><span class=o>/</span><span class=n>libcore</span><span class=o>/</span><span class=n>result</span><span class=p>.</span><span class=n>rs</span><span class=p>:</span><span class=mi>868</span><span class=w>
</span></span></span></code></pre></td></tr></table></div></div><h4 id=expect><span class=section-num>6.2.2</span> expect<a hidden class=anchor aria-hidden=true href=#expect>#</a></h4><p><code>expect()</code>和 <code>unwrap()</code>类似，只不过 <code>expect()</code>可以加上额外的信息：</p><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre tabindex=0 class=chroma><code><span class=lnt>1
</span><span class=lnt>2
</span><span class=lnt>3
</span><span class=lnt>4
</span><span class=lnt>5
</span></code></pre></td><td class=lntd><pre tabindex=0 class=chroma><code class=language-rust data-lang=rust><span class=line><span class=cl><span class=k>use</span><span class=w> </span><span class=n>std</span>::<span class=n>fs</span>::<span class=n>File</span><span class=p>;</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=k>fn</span> <span class=nf>main</span><span class=p>()</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=kd>let</span><span class=w> </span><span class=n>f</span><span class=w> </span><span class=o>=</span><span class=w> </span><span class=n>File</span>::<span class=n>open</span><span class=p>(</span><span class=s>&#34;hello.txt&#34;</span><span class=p>).</span><span class=n>expect</span><span class=p>(</span><span class=s>&#34;Failed to open hello.txt&#34;</span><span class=p>);</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span></code></pre></td></tr></table></div></div><p>出现错误的时候，除了显示应有的错误信息之外，还会显示你自定义的错误信息：</p><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre tabindex=0 class=chroma><code><span class=lnt>1
</span><span class=lnt>2
</span><span class=lnt>3
</span></code></pre></td><td class=lntd><pre tabindex=0 class=chroma><code class=language-fallback data-lang=fallback><span class=line><span class=cl>thread &#39;main&#39; panicked at &#39;Failed to open hello.txt: Error { repr: Os { code:
</span></span><span class=line><span class=cl>2, message: &#34;No such file or directory&#34; } }&#39;,
</span></span><span class=line><span class=cl>/stable-dist-rustc/build/src/libcore/result.rs:868
</span></span></code></pre></td></tr></table></div></div><p>以上代码来自 <a href=https://doc.rust-lang.org/book/second-edition/ch09-02-recoverable-errors-with-result.html>Rust book</a></p><h2 id=结语><span class=section-num>7</span> 结语<a hidden class=anchor aria-hidden=true href=#结语>#</a></h2><p>以上只是浅谈了 Rust 的错误处理，以及和 Java 的异常处理机制的简单比较，接下来我会 谈谈如何自定义<code>Error</code>以及使用
<code>erro_chain</code> 这个库来优雅地进行错误处理 :)</p><p>如果想了解更多关于 Rust 异常处理的内容，可以查阅 Rust book <a href=https://doc.rust-lang.org/book/second-edition/ch09-00-error-handling.html>Error handle</a></p><h2 id=参考><span class=section-num>8</span> 参考<a hidden class=anchor aria-hidden=true href=#参考>#</a></h2><ul><li><a href=http://tutorials.jenkov.com/exception-handling-strategies/propagating-exceptions.html>propagating exceptions</a></li><li><a href=https://doc.rust-lang.org/book/second-edition/>Rust book</a></li><li><a href=https://doc.rust-lang.org/stable/std/io/type.Result.html>IO Result</a></li></ul><div center class=qr-container><img src=/ox-hugo/qrcode_gh_e06d750e626f_1.jpg alt=qrcode_gh_e06d750e626f_1.jpg width=160px height=160px center=t class=qr-container>
公号同步更新，欢迎关注👻</div></div><footer class=post-footer><ul class=post-tags><li><a href=https://ramsayleung.github.io/zh/tags/rust/>rust</a></li><li><a href=https://ramsayleung.github.io/zh/tags/java/>java</a></li></ul><nav class=paginav><a class=prev href=https://ramsayleung.github.io/zh/post/2018/error_handle_in_rust_2/><span class=title>« 上一页</span><br><span>Rust的错误处理(二)</span>
</a><a class=next href=https://ramsayleung.github.io/zh/post/2017/search_eshell_history_like_fzf/><span class=title>下一页 »</span><br><span>Eshell实现fzf的历史命令搜索功能</span></a></nav><ul class=share-buttons><li><a target=_blank rel="noopener noreferrer" aria-label="share Rust的错误处理(一) on x" href="https://x.com/intent/tweet/?text=Rust%e7%9a%84%e9%94%99%e8%af%af%e5%a4%84%e7%90%86%28%e4%b8%80%29&amp;url=https%3a%2f%2framsayleung.github.io%2fzh%2fpost%2f2018%2ferror_handle_in_rust_1%2f&amp;hashtags=rust%2cjava"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentcolor"><path d="M512 62.554V449.446C512 483.97 483.97 512 449.446 512H62.554C28.03 512 0 483.97.0 449.446V62.554C0 28.03 28.029.0 62.554.0H449.446C483.971.0 512 28.03 512 62.554zM269.951 190.75 182.567 75.216H56L207.216 272.95 63.9 436.783h61.366L235.9 310.383l96.667 126.4H456L298.367 228.367l134-153.151H371.033zM127.633 110h36.468l219.38 290.065H349.5z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Rust的错误处理(一) on linkedin" href="https://www.linkedin.com/shareArticle?mini=true&amp;url=https%3a%2f%2framsayleung.github.io%2fzh%2fpost%2f2018%2ferror_handle_in_rust_1%2f&amp;title=Rust%e7%9a%84%e9%94%99%e8%af%af%e5%a4%84%e7%90%86%28%e4%b8%80%29&amp;summary=Rust%e7%9a%84%e9%94%99%e8%af%af%e5%a4%84%e7%90%86%28%e4%b8%80%29&amp;source=https%3a%2f%2framsayleung.github.io%2fzh%2fpost%2f2018%2ferror_handle_in_rust_1%2f"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentcolor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H62.554c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892zM160.461 423.278V197.561h-75.04v225.717h75.04zm270.539.0V293.839c0-69.333-37.018-101.586-86.381-101.586-39.804.0-57.634 21.891-67.617 37.266v-31.958h-75.021c.995 21.181.0 225.717.0 225.717h75.02V297.222c0-6.748.486-13.492 2.474-18.315 5.414-13.475 17.767-27.434 38.494-27.434 27.135.0 38.007 20.707 38.007 51.037v120.768H431zM123.448 88.722C97.774 88.722 81 105.601 81 127.724c0 21.658 16.264 39.002 41.455 39.002h.484c26.165.0 42.452-17.344 42.452-39.002-.485-22.092-16.241-38.954-41.943-39.002z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Rust的错误处理(一) on reddit" href="https://reddit.com/submit?url=https%3a%2f%2framsayleung.github.io%2fzh%2fpost%2f2018%2ferror_handle_in_rust_1%2f&title=Rust%e7%9a%84%e9%94%99%e8%af%af%e5%a4%84%e7%90%86%28%e4%b8%80%29"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentcolor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H62.554c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892zM446 265.638c0-22.964-18.616-41.58-41.58-41.58-11.211.0-21.361 4.457-28.841 11.666-28.424-20.508-67.586-33.757-111.204-35.278l18.941-89.121 61.884 13.157c.756 15.734 13.642 28.29 29.56 28.29 16.407.0 29.706-13.299 29.706-29.701.0-16.403-13.299-29.702-29.706-29.702-11.666.0-21.657 6.792-26.515 16.578l-69.105-14.69c-1.922-.418-3.939-.042-5.585 1.036-1.658 1.073-2.811 2.761-3.224 4.686l-21.152 99.438c-44.258 1.228-84.046 14.494-112.837 35.232-7.468-7.164-17.589-11.591-28.757-11.591-22.965.0-41.585 18.616-41.585 41.58.0 16.896 10.095 31.41 24.568 37.918-.639 4.135-.99 8.328-.99 12.576.0 63.977 74.469 115.836 166.33 115.836s166.334-51.859 166.334-115.836c0-4.218-.347-8.387-.977-12.493 14.564-6.47 24.735-21.034 24.735-38.001zM326.526 373.831c-20.27 20.241-59.115 21.816-70.534 21.816-11.428.0-50.277-1.575-70.522-21.82-3.007-3.008-3.007-7.882.0-10.889 3.003-2.999 7.882-3.003 10.885.0 12.777 12.781 40.11 17.317 59.637 17.317 19.522.0 46.86-4.536 59.657-17.321 3.016-2.999 7.886-2.995 10.885.008 3.008 3.011 3.003 7.882-.008 10.889zm-5.23-48.781c-16.373.0-29.701-13.324-29.701-29.698.0-16.381 13.328-29.714 29.701-29.714 16.378.0 29.706 13.333 29.706 29.714.0 16.374-13.328 29.698-29.706 29.698zM160.91 295.348c0-16.381 13.328-29.71 29.714-29.71 16.369.0 29.689 13.329 29.689 29.71.0 16.373-13.32 29.693-29.689 29.693-16.386.0-29.714-13.32-29.714-29.693z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Rust的错误处理(一) on facebook" href="https://facebook.com/sharer/sharer.php?u=https%3a%2f%2framsayleung.github.io%2fzh%2fpost%2f2018%2ferror_handle_in_rust_1%2f"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentcolor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H342.978V319.085h66.6l12.672-82.621h-79.272v-53.617c0-22.603 11.073-44.636 46.58-44.636H425.6v-70.34s-32.71-5.582-63.982-5.582c-65.288.0-107.96 39.569-107.96 111.204v62.971h-72.573v82.621h72.573V512h-191.104c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Rust的错误处理(一) on whatsapp" href="https://api.whatsapp.com/send?text=Rust%e7%9a%84%e9%94%99%e8%af%af%e5%a4%84%e7%90%86%28%e4%b8%80%29%20-%20https%3a%2f%2framsayleung.github.io%2fzh%2fpost%2f2018%2ferror_handle_in_rust_1%2f"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentcolor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H62.554c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892zm-58.673 127.703c-33.842-33.881-78.847-52.548-126.798-52.568-98.799.0-179.21 80.405-179.249 179.234-.013 31.593 8.241 62.428 23.927 89.612l-25.429 92.884 95.021-24.925c26.181 14.28 55.659 21.807 85.658 21.816h.074c98.789.0 179.206-80.413 179.247-179.243.018-47.895-18.61-92.93-52.451-126.81zM263.976 403.485h-.06c-26.734-.01-52.954-7.193-75.828-20.767l-5.441-3.229-56.386 14.792 15.05-54.977-3.542-5.637c-14.913-23.72-22.791-51.136-22.779-79.287.033-82.142 66.867-148.971 149.046-148.971 39.793.014 77.199 15.531 105.329 43.692 28.128 28.16 43.609 65.592 43.594 105.4-.034 82.149-66.866 148.983-148.983 148.984zm81.721-111.581c-4.479-2.242-26.499-13.075-30.604-14.571-4.105-1.495-7.091-2.241-10.077 2.241-2.986 4.483-11.569 14.572-14.182 17.562-2.612 2.988-5.225 3.364-9.703 1.12-4.479-2.241-18.91-6.97-36.017-22.23C231.8 264.15 222.81 249.484 220.198 245s-.279-6.908 1.963-9.14c2.016-2.007 4.48-5.232 6.719-7.847 2.24-2.615 2.986-4.484 4.479-7.472 1.493-2.99.747-5.604-.374-7.846-1.119-2.241-10.077-24.288-13.809-33.256-3.635-8.733-7.327-7.55-10.077-7.688-2.609-.13-5.598-.158-8.583-.158-2.986.0-7.839 1.121-11.944 5.604-4.105 4.484-15.675 15.32-15.675 37.364.0 22.046 16.048 43.342 18.287 46.332 2.24 2.99 31.582 48.227 76.511 67.627 10.685 4.615 19.028 7.371 25.533 9.434 10.728 3.41 20.492 2.929 28.209 1.775 8.605-1.285 26.499-10.833 30.231-21.295 3.732-10.464 3.732-19.431 2.612-21.298-1.119-1.869-4.105-2.99-8.583-5.232z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Rust的错误处理(一) on telegram" href="https://telegram.me/share/url?text=Rust%e7%9a%84%e9%94%99%e8%af%af%e5%a4%84%e7%90%86%28%e4%b8%80%29&amp;url=https%3a%2f%2framsayleung.github.io%2fzh%2fpost%2f2018%2ferror_handle_in_rust_1%2f"><svg viewBox="2 2 28 28" height="30" width="30" fill="currentcolor"><path d="M26.49 29.86H5.5a3.37 3.37.0 01-2.47-1 3.35 3.35.0 01-1-2.47V5.48A3.36 3.36.0 013 3 3.37 3.37.0 015.5 2h21A3.38 3.38.0 0129 3a3.36 3.36.0 011 2.46V26.37a3.35 3.35.0 01-1 2.47 3.38 3.38.0 01-2.51 1.02zm-5.38-6.71a.79.79.0 00.85-.66L24.73 9.24a.55.55.0 00-.18-.46.62.62.0 00-.41-.17q-.08.0-16.53 6.11a.59.59.0 00-.41.59.57.57.0 00.43.52l4 1.24 1.61 4.83a.62.62.0 00.63.43.56.56.0 00.4-.17L16.54 20l4.09 3A.9.9.0 0021.11 23.15zM13.8 20.71l-1.21-4q8.72-5.55 8.78-5.55c.15.0.23.0.23.16a.18.18.0 010 .06s-2.51 2.3-7.52 6.8z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Rust的错误处理(一) on ycombinator" href="https://news.ycombinator.com/submitlink?t=Rust%e7%9a%84%e9%94%99%e8%af%af%e5%a4%84%e7%90%86%28%e4%b8%80%29&u=https%3a%2f%2framsayleung.github.io%2fzh%2fpost%2f2018%2ferror_handle_in_rust_1%2f"><svg width="30" height="30" viewBox="0 0 512 512" fill="currentcolor" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"><path d="M449.446.0C483.971.0 512 28.03 512 62.554V449.446C512 483.97 483.97 512 449.446 512H62.554C28.03 512 0 483.97.0 449.446V62.554C0 28.03 28.029.0 62.554.0H449.446zM183.8767 87.9921h-62.034L230.6673 292.4508V424.0079h50.6655V292.4508L390.1575 87.9921H328.1233L256 238.2489z"/></svg></a></li></ul></footer><section><h2>Comments</h2><div id=comments-giscus></div></section><script type=text/javascript>function getCurrentTheme(){return document.documentElement.getAttribute("data-theme")||document.body.classList.contains("dark")?"dark":"light"}function setGiscusTheme(e=!1){const s=e?"dark":"light";var n,t=document.querySelector(".giscus-frame");t&&(n=new URL(t.src),n.searchParams.set("theme",s),t.src=n.toString())}function loadComment(e=!1){const n="zh"=="zh",t=document.getElementById("comments-giscus");if(t!==null&&!t.hasAttribute("data-giscus-loaded")){console.log("Initial giscus load");const s=document.createElement("script");s.setAttribute("src","https://giscus.app/client.js"),s.setAttribute("data-repo","ramsayleung/comment"),s.setAttribute("data-repo-id","MDEwOlJlcG9zaXRvcnkzMDk2NjQ1NDk="),s.setAttribute("data-category","General"),s.setAttribute("data-category-id","DIC_kwDOEnUbJc4Cltnz"),s.setAttribute("data-mapping","pathname"),s.setAttribute("data-strict","0"),s.setAttribute("data-reactions-enabled","1"),s.setAttribute("data-emit-metadata","0"),s.setAttribute("data-input-position","bottom"),s.setAttribute("data-theme",e?"dark":"light"),s.setAttribute("crossorigin","anonymous"),s.setAttribute("data-lang",n?"zh-CN":"en"),s.setAttribute("async","true"),t.appendChild(s),t.setAttribute("data-giscus-loaded","true")}}let currentTheme=getCurrentTheme();loadComment(currentTheme==="dark");const themeObserver=new MutationObserver(e=>{e.forEach(e=>{if(e.type==="attributes"&&e.attributeName==="class"){const e=getCurrentTheme();e!==currentTheme&&(currentTheme=e,setGiscusTheme(currentTheme==="dark"))}})});themeObserver.observe(document.body,{attributes:!0,attributeFilter:["class"]})</script></article></main><footer class=footer><span>See this site&rsquo;s source code <a href=https://github.com/ramsayleung/ramsayleung.github.io>here</a>, licensed under GPLv3 ·</span> ·
<span>Powered by
<a href=https://gohugo.io/ rel="noopener noreferrer" target=_blank>Hugo</a> &
        <a href=https://github.com/adityatelange/hugo-PaperMod/ rel=noopener target=_blank>PaperMod</a></span></footer><a href=#top aria-label="go to top" title="Go to Top (Alt + G)" class=top-link id=top-link accesskey=g><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 6" fill="currentcolor"><path d="M12 6H0l6-6z"/></svg></a><script>let menu=document.getElementById("menu");menu&&(menu.scrollLeft=localStorage.getItem("menu-scroll-position"),menu.onscroll=function(){localStorage.setItem("menu-scroll-position",menu.scrollLeft)}),document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(e){e.preventDefault();var t=this.getAttribute("href").substr(1);window.matchMedia("(prefers-reduced-motion: reduce)").matches?document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView():document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView({behavior:"smooth"}),t==="top"?history.replaceState(null,null," "):history.pushState(null,null,`#${t}`)})})</script><script>var mybutton=document.getElementById("top-link");window.onscroll=function(){document.body.scrollTop>800||document.documentElement.scrollTop>800?(mybutton.style.visibility="visible",mybutton.style.opacity="1"):(mybutton.style.visibility="hidden",mybutton.style.opacity="0")}</script><script>document.getElementById("theme-toggle").addEventListener("click",()=>{document.body.className.includes("dark")?(document.body.classList.remove("dark"),localStorage.setItem("pref-theme","light")):(document.body.classList.add("dark"),localStorage.setItem("pref-theme","dark"))})</script></body></html>